---
title: "Projects"
---

## Project 1
**The Whales of Iceland: Monitoring populations in regard to whaling**

I used multiple publicly available datasets to create a project investigating the effects of whaling on whale populations, based on the whale species that did and didn't get protected status from the Icelandic government. I found that the species for which whaling is allowed are experiencing rapid declines. Possibly more alarming, I found that every time the Icelandic government granted permission for a species to be hunted, the government stopped all population tracking of that species, stopped funding population research of that species, and overall tried to mask the effects these policies were having on the ecosystem. Using datasets collected from nearby countries and marine conservation non-profit organizations, I was able to map the decline of these species.

## Project 2
**Investigating Hemlock Woolly Adelgid: Determining relationships between site characteristics, tree morphology, and overall HWA infestation.**

I studied a Hemlock stand infested with Hemlock Woolly Adelgid (HWA) at Yale Myers forest. The stand was along a steep ridgeline, the bottom of which bordered a large pond, the top of which was arid and exposed to the elemnets. I investigated variables of tree growth, soil characteristics, and landscape attributes in relation to HWA infestation. For soil characteristics, I found that Calcium, Aluminium, and Iron all had significant relationships with HWA. Additionally, increased soil moisture and the lower elevation significantly decreased the levels of HWA. Lastly, at the tree level I found that the level in the canopy also significantly related to the amount of HWA infestation. In conclusion, there are factors in the soil, tree, and landscape that can significantly alter HWA infestation.

